version: '3.8'

services:
  web:
    image: vishakhak1/django-app:latest   # Your Docker Hub image
    ports:
      - "8080:8000"
    networks:
      - myapp_app-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - myapp_app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  myapp_app-net:
    external: true

volumes:
  pgdata:
